export type Dug = {
    artist: string
    artist_gulb: string
    title: string
    title_gulb: string
    id: string
    year: number
    type: string
    bc_id: string
    bc_link: string
    cover_s: string
    cover_l: string
}

const dugs: Dug[] = [
    {
        "artist": "Dug Alcedo",
        "artist_gulb": "dug ol'see'do",
        "title": "Hard Rock EP",
        "title_gulb": "hor'd rok e'p",
        id: "DUG044b",
        year: 2024,
        type: "EP",
        bc_id: "3557368383",
        bc_link: "https://dugalcedo.bandcamp.com/album/hard-rock-ep",
        "cover_s": "/images/acxs/DUG044b.jpg",
        "cover_l": "/images/acs/DUG044b.jpg",
    },
    {
        "artist": "Dug Alcedo",
        "artist_gulb": "dug ol'se'doo",
        "title": "Humans",
        "title_gulb": "h'yuu'mn'z",
        "id": "DUG044",
        "year": 2024,
        "type": "album",
        "bc_id": "1827608274",
        "bc_link": "https://dugalcedo.bandcamp.com/album/humans",
        "cover_s": "/images/acxs/DUG044.jpg",
        "cover_l": "/images/acs/DUG044.jpg"
    },
    {
        "artist": "Dug Alcedo",
        "artist_gulb": "dug ol'se'doo",
        "title": "Goos Beyond",
        "title_gulb": "guuz bee'yon'd",
        "id": "DUG043",
        "year": 2022,
        "type": "album",
        "bc_id": "3909499862",
        "bc_link": "https://dugalcedo.bandcamp.com/album/goos-beyond",
        "cover_s": "/images/acxs/DUG043.jpg",
        "cover_l": "/images/acs/DUG043.jpg"
    },
    {
        "artist": "Dew for Slug",
        "artist_gulb": "duu f s'lug",
        "title": "I-15 Dream",
        "title_gulb": "ii-15 d'reem",
        "id": "DUG042c",
        "year": 2021,
        "type": "collab",
        "bc_id": "2686980342",
        "bc_link": "https://pelagoramrecordings.bandcamp.com/album/i-15-dream",
        "cover_s": "/images/acxs/DUG042c.jpg",
        "cover_l": "/images/acs/DUG042c.jpg"
    },
    {
        "artist": "Dug Alcedo",
        "artist_gulb": "dug ol'se'doo",
        "title": "Starship Comino (Cave version)",
        "title_gulb": "s'tor'Sip koo'mee'noo (kaav vr'Zn)",
        "id": "DUG042b",
        "year": 2021,
        "type": "single",
        "bc_id": "397204052",
        "bc_link": "https://dugalcedo.bandcamp.com/album/2021-06-18-thos-album-release-show",
        "cover_s": "/images/acxs/DUG042b.jpg",
        "cover_l": "/images/acs/DUG042b.jpg"
    },
    {
        "artist": "Dug Alcedo",
        "artist_gulb": "dug ol'se'doo",
        "title": "Big Fish eat Little Fish",
        "title_gulb": "big fiS eet li'tl fiS",
        "id": "DUG042",
        "year": 2021,
        "type": "album",
        "bc_id": "1528786253",
        "bc_link": "https://dugalcedo.bandcamp.com/album/big-fish-eat-little-fish",
        "cover_s": "/images/acxs/DUG042.jpg",
        "cover_l": "/images/acs/DUG042.jpg"
    },
    {
        "artist": "Dug Alcedo",
        "artist_gulb": "dug ol'se'doo",
        "title": "Bonito",
        "title_gulb": "boo'nee'too",
        "id": "DUG041b",
        "year": 2021,
        "type": "single",
        "bc_id": "1724980487",
        "bc_link": "https://dugalcedo.bandcamp.com/album/bonito-single",
        "cover_s": "/images/acxs/DUG041b.jpg",
        "cover_l": "/images/acs/DUG041b.jpg"
    },
    {
        "artist": "Dug Alcedo",
        "artist_gulb": "dug ol'se'doo",
        "title": "Comber",
        "title_gulb": "koom'b'r",
        "id": "DUG041",
        "year": 2020,
        "type": "album",
        "bc_id": "3522925184",
        "bc_link": "https://dugalcedo.bandcamp.com/album/comber",
        "cover_s": "/images/acxs/DUG041.jpg",
        "cover_l": "/images/acs/DUG041.jpg"
    },
    {
        "artist": "Dug Alcedo",
        "artist_gulb": "dug ol'se'doo",
        "title": "Pinya",
        "title_gulb": "pin'yx",
        "id": "DUG040b",
        "year": 2020,
        "type": "single",
        "bc_id": "685242952",
        "bc_link": "https://dugalcedo.bandcamp.com/album/pinya-borealis-go-fast",
        "cover_s": "/images/acxs/DUG040b.jpg",
        "cover_l": "/images/acs/DUG040b.jpg"
    },
    {
        "artist": "Dug Alcedo",
        "artist_gulb": "dug ol'se'doo",
        "title": "XL",
        "title_gulb": "ek's el",
        "id": "DUG040",
        "year": 2020,
        "type": "album",
        "bc_id": "3245678441",
        "bc_link": "https://dugalcedo.bandcamp.com/album/xl",
        "cover_s": "/images/acxs/DUG040.jpg",
        "cover_l": "/images/acs/DUG040.jpg"
    },
    {
        "artist": "Dug Alcedo",
        "artist_gulb": "dug ol'se'doo",
        "title": "Hell Scenery",
        "title_gulb": "hel see'nx'ree",
        "id": "DUG039",
        "year": 2020,
        "type": "album",
        "bc_id": "3813412774",
        "bc_link": "https://dugalcedo.bandcamp.com/album/hell-scenery",
        "cover_s": "/images/acxs/DUG039.jpg",
        "cover_l": "/images/acs/DUG039.jpg"
    },
    {
        "artist": "Dug Alcedo",
        "artist_gulb": "dug ol'se'doo",
        "title": "Casked Acid in Black Sheep Canyon",
        "title_gulb": "kas'k'd a'sid in b'lak Sip kan'yn",
        "id": "DUG038",
        "year": 2019,
        "type": "album",
        "bc_id": "117522757",
        "bc_link": "https://dugalcedo.bandcamp.com/album/casked-acid-in-black-sheep-canyon",
        "cover_s": "/images/acxs/DUG038.jpg",
        "cover_l": "/images/acs/DUG038.jpg"
    },
    {
        "artist": "Dug Alcedo",
        "artist_gulb": "dug ol'se'doo",
        "title": "Possum with Apple",
        "title_gulb": "po'sm w a'pl",
        "id": "DUG037",
        "year": 2019,
        "type": "album",
        "bc_id": "3517251765",
        "bc_link": "https://dugalcedo.bandcamp.com/album/possum-with-apple",
        "cover_s": "/images/acxs/DUG037.jpg",
        "cover_l": "/images/acs/DUG037.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Soundcloud 2018",
        "title_gulb": "saun'd k'laud 2018",
        "id": "DUG036b",
        "year": 2019,
        "type": "ep",
        "bc_id": "1323647648",
        "bc_link": "https://firstdog.bandcamp.com/album/soundcloud-2018",
        "cover_s": "/images/acxs/DUG036b.jpg",
        "cover_l": "/images/acs/DUG036b.jpg"
    },
    {
        "artist": "Dug Alcedo",
        "artist_gulb": "dug ol'se'doo",
        "title": "Guard Goose",
        "title_gulb": "gor'd guus",
        "id": "DUG036",
        "year": 2019,
        "type": "mini-album",
        "bc_id": "4110385408",
        "bc_link": "https://dugalcedo.bandcamp.com/album/guard-goose",
        "cover_s": "/images/acxs/DUG036.jpg",
        "cover_l": "/images/acs/DUG036.jpg"
    },
    {
        "artist": "Dug Alcedo",
        "artist_gulb": "dug ol'se'doo",
        "title": "Fish Antlers",
        "title_gulb": "fiS an't'lr'z",
        "id": "DUG035",
        "year": 2019,
        "type": "album",
        "bc_id": "2585332977",
        "bc_link": "https://dugalcedo.bandcamp.com/album/fish-antlers",
        "cover_s": "/images/acxs/DUG035.jpg",
        "cover_l": "/images/acs/DUG035.jpg"
    },
    {
        "artist": "Dug Alcedo",
        "artist_gulb": "dug ol'se'doo",
        "title": "Money Snakes",
        "title_gulb": "mu'nee s'naak's",
        "id": "DUG034",
        "year": 2019,
        "type": "album",
        "bc_id": "3239889775",
        "bc_link": "https://dugalcedo.bandcamp.com/album/money-snakes",
        "cover_s": "/images/acxs/DUG034.jpg",
        "cover_l": "/images/acs/DUG034.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Isyiau",
        "title_gulb": "i'see'yau",
        "id": "DUG033",
        "year": 2018,
        "type": "album",
        "bc_id": "2439411014",
        "bc_link": "https://firstdog.bandcamp.com/album/isyiau",
        "cover_s": "/images/acxs/DUG033.jpg",
        "cover_l": "/images/acs/DUG033.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Separation Newdrum",
        "title_gulb": "se'px'raa'Sn nuu'd'rum",
        "id": "DUG032b",
        "year": 2018,
        "type": "ep",
        "bc_id": "3996183796",
        "bc_link": "https://firstdog.bandcamp.com/album/separation-newdrum",
        "cover_s": "/images/acxs/DUG032b.jpg",
        "cover_l": "/images/acs/DUG032b.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Moosic",
        "title_gulb": "muu'sik",
        "id": "DUG032",
        "year": 2018,
        "type": "album",
        "bc_id": "3233370815",
        "bc_link": "https://firstdog.bandcamp.com/album/moosic",
        "cover_s": "/images/acxs/DUG032.jpg",
        "cover_l": "/images/acs/DUG032.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Bird in a Cave (echo)",
        "title_gulb": "br'd in x kaav (e'koo)",
        "id": "DUG031",
        "year": 2017,
        "type": "album",
        "bc_id": "4071937567",
        "bc_link": "https://firstdog.bandcamp.com/album/bird-in-a-cave-(echo)",
        "cover_s": "/images/acxs/DUG031.jpg",
        "cover_l": "/images/acs/DUG031.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Friends Fever",
        "title_gulb": "f'ren'z fee'vr",
        "id": "DUG030",
        "year": 2017,
        "type": "album",
        "bc_id": "3613936290",
        "bc_link": "https://firstdog.bandcamp.com/album/friends-fever",
        "cover_s": "/images/acxs/DUG030.jpg",
        "cover_l": "/images/acs/DUG030.jpg"
    },
    {
        "artist": "Loukas",
        "artist_gulb": "luu'ks",
        "title": "Loukas 1",
        "title_gulb": "luu'ks 1",
        "id": "DUG029",
        "year": 2016,
        "type": "mini-album",
        "bc_id": "2499258239",
        "bc_link": "https://firstdog.bandcamp.com/album/loukas-1",
        "cover_s": "/images/acxs/DUG029.jpg",
        "cover_l": "/images/acs/DUG029.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Bird in a Cave",
        "title_gulb": "br'd in x kaav",
        "id": "DUG028",
        "year": 2016,
        "type": "album",
        "bc_id": "3660544442",
        "bc_link": "https://firstdog.bandcamp.com/album/bird-in-a-cave",
        "cover_s": "/images/acxs/DUG028.jpg",
        "cover_l": "/images/acs/DUG028.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Ow Cute",
        "title_gulb": "au k'yuut",
        "id": "DUG027b",
        "year": 2016,
        "type": "ep",
        "bc_id": "3093688189",
        "bc_link": "https://firstdog.bandcamp.com/album/ow-cute",
        "cover_s": "/images/acxs/DUG027b.jpg",
        "cover_l": "/images/acs/DUG027b.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Aw Cute",
        "title_gulb": "o'o k'yuut",
        "id": "DUG027",
        "year": 2015,
        "type": "album",
        "bc_id": "2561784264",
        "bc_link": "https://firstdog.bandcamp.com/album/aw-cute",
        "cover_s": "/images/acxs/DUG027.jpg",
        "cover_l": "/images/acs/DUG027.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Lucoizo",
        "title_gulb": "luuk'wo'soo",
        "id": "DUG026",
        "year": 2014,
        "type": "album",
        "bc_id": "1203318470",
        "bc_link": "https://firstdog.bandcamp.com/album/lucoizo",
        "cover_s": "/images/acxs/DUG026.jpg",
        "cover_l": "/images/acs/DUG026.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Gabaraptor",
        "title_gulb": "ga'bx'rap'tr",
        "id": "DUG025",
        "year": 2014,
        "type": "album",
        "bc_id": "2972472047",
        "bc_link": "https://firstdog.bandcamp.com/album/gabaraptor",
        "cover_s": "/images/acxs/DUG025.jpg",
        "cover_l": "/images/acs/DUG025.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Paranoid Cartoons",
        "title_gulb": "pe'rx'noid kor'tuun'z",
        "id": "DUG024",
        "year": 2014,
        "type": "album",
        "bc_id": "1920506124",
        "bc_link": "https://firstdog.bandcamp.com/album/paranoid-cartoons",
        "cover_s": "/images/acxs/DUG024.jpg",
        "cover_l": "/images/acs/DUG024.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Feeder",
        "title_gulb": "feed'r",
        "id": "DUG023",
        "year": 2013,
        "type": "album",
        "bc_id": "1015688186",
        "bc_link": "https://firstdog.bandcamp.com/album/feeder",
        "cover_s": "/images/acxs/DUG023.jpg",
        "cover_l": "/images/acs/DUG023.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Volt Welve",
        "title_gulb": "vool't wel'v",
        "id": "DUG022",
        "year": 2013,
        "type": "album",
        "bc_id": "706814123",
        "bc_link": "https://firstdog.bandcamp.com/album/volt-welve",
        "cover_s": "/images/acxs/DUG022.jpg",
        "cover_l": "/images/acs/DUG022.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Feeble",
        "title_gulb": "fee'bl",
        "id": "DUG021",
        "year": 2012,
        "type": "album",
        "bc_id": "3858484618",
        "bc_link": "https://firstdog.bandcamp.com/album/feeble",
        "cover_s": "/images/acxs/DUG021.jpg",
        "cover_l": "/images/acs/DUG021.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Language from the Grip",
        "title_gulb": "leq'wj fm Dx g'rip",
        "id": "DUG020",
        "year": 2012,
        "type": "album",
        "bc_id": "3385909548",
        "bc_link": "https://firstdog.bandcamp.com/album/language-from-the-grip",
        "cover_s": "/images/acxs/DUG020.jpg",
        "cover_l": "/images/acs/DUG020.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Camel 2",
        "title_gulb": "ka'ml 2",
        "id": "DUG019",
        "year": 2012,
        "type": "mini-album",
        "bc_id": "3116491278",
        "bc_link": "https://firstdog.bandcamp.com/album/camel-2",
        "cover_s": "/images/acxs/DUG019.jpg",
        "cover_l": "/images/acs/DUG019.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Videogame Soundtrack",
        "title_gulb": "naa'Sn v me'mx'ree'z",
        "id": "DUG018",
        "year": 2012,
        "type": "album",
        "bc_id": "2695211125",
        "bc_link": "https://firstdog.bandcamp.com/album/videogame-soundtrack",
        "cover_s": "/images/acxs/DUG018.jpg",
        "cover_l": "/images/acs/DUG018.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Untrue/Parrot",
        "title_gulb": "un't'ruu/pe'rt",
        "id": "DUG017",
        "year": 2012,
        "type": "album",
        "bc_id": "2361478125",
        "bc_link": "https://firstdog.bandcamp.com/album/parrot",
        "cover_s": "/images/acxs/DUG017.jpg",
        "cover_l": "/images/acs/DUG017.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Landing",
        "title_gulb": "lan'd'q",
        "id": "DUG016",
        "year": 2011,
        "type": "mini-album",
        "bc_id": "2607287906",
        "bc_link": "https://firstdog.bandcamp.com/album/landing",
        "cover_s": "/images/acxs/DUG016.jpg",
        "cover_l": "/images/acs/DUG016.jpg"
    },
    {
        "artist": "First Dog",
        "artist_gulb": "fr's't dog",
        "title": "Corecore",
        "title_gulb": "koor'koor",
        "id": "DUG015",
        "year": 2011,
        "type": "album",
        "bc_id": "3776743387",
        "bc_link": "https://firstdog.bandcamp.com/album/corecore",
        "cover_s": "/images/acxs/DUG015.jpg",
        "cover_l": "/images/acs/DUG015.jpg"
    },
    {
        "artist": "FDVCE & Dylan Jones",
        "artist_gulb": "f'd'v's'x & di'ln joon'z",
        "title": "Kondo Split",
        "title_gulb": "koon'doo s'p'lit",
        "id": "DUG013b",
        "year": 2010,
        "type": "split",
        "bc_id": "1365005315",
        "bc_link": "https://firstdog.bandcamp.com/album/kond-split",
        "cover_s": "/images/acxs/DUG013b.jpg",
        "cover_l": "/images/acs/DUG013b.jpg"
    },
    {
        "artist": "FDVCE",
        "artist_gulb": "f'd'v's'x",
        "title": "Every Machine On",
        "title_gulb": "ev'ree mx'Seen on",
        "id": "DUG013",
        "year": 2010,
        "type": "album",
        "bc_id": "3787772774",
        "bc_link": "https://firstdog.bandcamp.com/album/every-machine-on",
        "cover_s": "/images/acxs/DUG013.jpg",
        "cover_l": "/images/acs/DUG013.jpg"
    },
    {
        "artist": "FDVCE",
        "artist_gulb": "f'd'v's'x",
        "title": "Stoner",
        "title_gulb": "s'toon'r",
        "id": "DUG012",
        "year": 2010,
        "type": "album",
        "bc_id": "709445185",
        "bc_link": "https://firstdog.bandcamp.com/album/stoner",
        "cover_s": "/images/acxs/DUG012.jpg",
        "cover_l": "/images/acs/DUG012.jpg"
    },
    {
        "artist": "FDVCE",
        "artist_gulb": "f'd'v's'x",
        "title": "Colossus Archosaur",
        "title_gulb": "kx'lo'ss or'kx'soor",
        "id": "DUG011",
        "year": 2010,
        "type": "album",
        "bc_id": "3450513756",
        "bc_link": "https://firstdog.bandcamp.com/album/colossus-archosaur",
        "cover_s": "/images/acxs/DUG011.jpg",
        "cover_l": "/images/acs/DUG011.jpg"
    },
    {
        "artist": "FDVCE",
        "artist_gulb": "f'd'v's'x",
        "title": "Provenance Fen",
        "title_gulb": "p'ro'vx'nn's fen",
        "id": "DUG000b",
        "year": 2009,
        "type": "compilation",
        "bc_id": "3261715349",
        "bc_link": "https://firstdog.bandcamp.com/album/provenance-fen",
        "cover_s": "/images/acxs/DUG000b.jpg",
        "cover_l": "/images/acs/DUG000b.jpg"
    },
    {
        "artist": "FDVCE",
        "artist_gulb": "f'd'v's'x",
        "title": "Primeval Dross",
        "title_gulb": "p'rii'mee'vl d'ros",
        "id": "DUG000a",
        "year": 2008,
        "type": "compilation",
        "bc_id": "3292042228",
        "bc_link": "https://firstdog.bandcamp.com/album/primeval-dross",
        "cover_s": "/images/acxs/DUG000a.jpg",
        "cover_l": "/images/acs/DUG000a.jpg"
    }
]

export default dugs