export const flagCodeMap: Record<string, string | null> = {
    "Afghanistan": "af",
    "Albania": "al",
    "Algeria": "dz",
    "Angola": "ao",
    "Argentina": "ar",
    "Armenia": "am",
    "Aruba": "aw",
    "Australia": "au",
    "Austria": "at",
    "Azerbaijan": "az",
    "Bahamas": "bs",
    "Bahrain": "bh",
    "Bangladesh": "bd",
    "Barbados": "bb",
    "Belarus": "by",
    "Belgium": "be",
    "Belize": "bz",
    "Benin": "bj",
    "Bhutan": "bt",
    "Bolivia": "bo",
    "Bosnia and Herzegovina": "ba",
    "Botswana": "bw",
    "Brazil": "br",
    "Brunei": "bn",
    "Bulgaria": "bg",
    "Burkina Faso": "bf",
    "Burundi": "bi",
    "Cabo Verde": "cv",
    "Cambodia": "kh",
    "Cameroon": "cm",
    "Canada": "ca",
    "Central African Republic": "cf",
    "Chad": "td",
    "Chile": "cl",
    "China": "cn",
    "Colombia": "co",
    "Comoros": "km",
    "Costa Rica": "cr",
    "Croatia": "hr",
    "Cuba": "cu",
    "Curaçao": "cw",
    "Cyprus": "cy",
    "Czechia": "cz",
    "Côte d'Ivoire": "ci",
    "Democratic Republic of the Congo": "cd",
    "Denmark": "dk",
    "Djibouti": "dj",
    "Dominican Republic": "do",
    "Ecuador": "ec",
    "Egypt": "eg",
    "El Salvador": "sv",
    "Equatorial Guinea": "gq",
    "Eritrea": "er",
    "Estonia": "ee",
    "Ethiopia": "et",
    "Fiji": "fj",
    "Finland": "fi",
    "France": "fr",
    "French Guiana": "gf",
    "French Polynesia": "pf",
    "Gabon": "ga",
    "Gambia": "gm",
    "Georgia": "ge",
    "Germany": "de",
    "Ghana": "gh",
    "Greece": "gr",
    "Guatemala": "gt",
    "Guinea": "gn",
    "Guinea-Bissau": "gw",
    "Guyana": "gy",
    "Haiti": "ht",
    "Honduras": "hn",
    "Hong Kong": "hk",
    "Hungary": "hu",
    "Iceland": "is",
    "India": "in",
    "Indonesia": "id",
    "Iran": "ir",
    "Iraq": "iq",
    "Ireland": "ie",
    "Israel": null,
    "Italy": "it",
    "Jamaica": "jm",
    "Japan": "jp",
    "Jersey": "je",
    "Jordan": "jo",
    "Kazakhstan": "kz",
    "Kenya": "ke",
    "Kosovo": "xk",
    "Kuwait": "kw",
    "Kyrgyzstan": "kg",
    "Laos": "la",
    "Latvia": "lv",
    "Lebanon": "lb",
    "Lesotho": "ls",
    "Liberia": "lr",
    "Libya": "ly",
    "Lithuania": "lt",
    "Luxembourg": "lu",
    "Macau": "mo",
    "Madagascar": "mg",
    "Malawi": "mw",
    "Malaysia": "my",
    "Maldives": "mv",
    "Mali": "ml",
    "Malta": "mt",
    "Martinique": "mq",
    "Mauritania": "mr",
    "Mauritius": "mu",
    "Mayotte": "yt",
    "Moldova": "md",
    "Mongolia": "mn",
    "Montenegro": "me",
    "Morocco": "ma",
    "Mozambique": "mz",
    "Myanmar": "mm",
    "México": "mx",
    "Namibia": "na",
    "Nepal": "np",
    "Netherlands": "nl",
    "New Caledonia": "nc",
    "New Zealand": "nz",
    "Nicaragua": "ni",
    "Niger": "ne",
    "Nigeria": "ng",
    "North Korea": "kp",
    "North Macedonia": "mk",
    "Norway": "no",
    "Oman": "om",
    "Pakistan": "pk",
    "Palestine": "ps",
    "Panama": "pa",
    "Papua New Guinea": "pg",
    "Paraguay": "py",
    "Peru": "pe",
    "Philippines": "ph",
    "Poland": "pl",
    "Portugal": "pt",
    "Puerto Rico": "pr",
    "Qatar": "qa",
    "Republic of the Congo": "cg",
    "Romania": "ro",
    "Russia": "ru",
    "Rwanda": "rw",
    "Réunion": "re",
    "Samoa": "ws",
    "Saudi Arabia": "sa",
    "Senegal": "sn",
    "Serbia": "rs",
    "Sierra Leone": "sl",
    "Singapore": "sg",
    "Slovakia": "sk",
    "Slovenia": "si",
    "Solomon Islands": "sb",
    "Somalia": "so",
    "South Africa": "za",
    "South Korea": "kr",
    "South Sudan": "ss",
    "Spain": "es",
    "Sri Lanka": "lk",
    "Sudan": "sd",
    "Suriname": "sr",
    "Swaziland": "sz",
    "Sweden": "se",
    "Switzerland": "ch",
    "Syria": "sy",
    "São Tomé and Príncipe": "st",
    "Taiwan": "tw",
    "Tajikistan": "tj",
    "Tanzania": "tz",
    "Thailand": "th",
    "Timor-Leste": "tl",
    "Togo": "tg",
    "Tonga": "to",
    "Trinidad and Tobago": "tt",
    "Tunisia": "tn",
    "Turkey": "tr",
    "Turkmenistan": "tm",
    "Uganda": "ug",
    "Ukraine": "ua",
    "United Arab Emirates": "ae",
    "United Kingdom": "gb",
    "United States": "us",
    "Uruguay": "uy",
    "Uzbekistan": "uz",
    "Vanuatu": "vu",
    "Venezuela": "ve",
    "Vietnam": "vn",
    "Western Sahara": "eh",
    "Yemen": "ye",
    "Zambia": "zm",
    "Zimbabwe": "zw",
    "US Alabama": "us-al",
    "US Alaska": "us-ak",
    "US Arizona": "us-az",
    "US Arkansas": "us-ar",
    "US California": "us-ca",
    "US Colorado": "us-co",
    "US Connecticut": "us-ct",
    "US Delaware": "us-de",
    "US District of Columbia": "us-dc",
    "US Florida": "us-fl",
    "US Georgia": "us-ga",
    "US Hawaii": "us-hi",
    "US Idaho": "us-id",
    "US Illinois": "us-il",
    "US Indiana": "us-in",
    "US Iowa": "us-ia",
    "US Kansas": "us-ks",
    "US Kentucky": "us-ky",
    "US Louisiana": "us-la",
    "US Maine": "us-me",
    "US Maryland": "us-md",
    "US Massachusetts": "us-ma",
    "US Michigan": "us-mi",
    "US Minnesota": "us-mn",
    "US Mississippi": "us-ms",
    "US Missouri": "us-mo",
    "US Montana": "us-mt",
    "US Nebraska": "us-ne",
    "US Nevada": "us-nv",
    "US New Hampshire": "us-nh",
    "US New Jersey": "us-nj",
    "US New Mexico": "us-nm",
    "US New York": "us-ny",
    "US North Carolina": "us-nc",
    "US North Dakota": "us-nd",
    "US Ohio": "us-oh",
    "US Oklahoma": "us-ok",
    "US Oregon": "us-or",
    "US Pennsylvania": "us-pa",
    "US Rhode Island": "us-ri",
    "US South Carolina": "us-sc",
    "US South Dakota": "us-sd",
    "US Tennessee": "us-tn",
    "US Texas": "us-tx",
    "US Utah": "us-ut",
    "US Vermont": "us-vt",
    "US Virginia": "us-va",
    "US Washington": "us-wa",
    "US West Virginia": "us-wv",
    "US Wisconsin": "us-wi",
    "US Wyoming": "us-wy",
    "World": "un",
    "Europe": "eu"
}

export type FlagWidth = 20 | 40 | 80 | 160 | 320 | 640 | 1280 | 2560

export const stringToFlagImgUrl = (str: string, width: FlagWidth = 40): string | null => {
    // assume the string will already be formatted like "US California" if it's us
    const code = flagCodeMap[str]
    return code ? `https://flagcdn.com/w${width}/${code}.png` : null
}